### ISSUE TITLE
Add arm and arm64 (aarch64) support

### ISSUE THREAD

**Issue by samip5** [ogarcia/docker-tor#2]
Unfortunately it seems like your container is only usable on AMD64, but not on ARM64.

```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by ogarcia** [comment]
Sorry, but at this moment CircleCI don't support ARM architecture :disappointed:

**Comment by samip5** [comment]
Why not use Travis CI? It does support arm.

**Comment by ogarcia** [comment]
I have all my pipelines in Circle and don't use Tor in ARM. Anyway is very easy build this docker image in your ARM machine, simply clone the repo and run:
```
make docker-build
```
